#!/bin/bash
echo --------------------------------------------------- >> ~/bin/restore.log
date >> ~/bin/restore.log
# home dir restore dry run, remove -n to do actual run
rsync -nvarz --stats --log-file ~/bin/restore.log /media/Backups/system/home/user/ /home/user/

# to restore from a remote system use something like this
# this will keep files that were updated on the destination
# you can make a foreced sync and DELETE these that are not on the source! - use --delete key
#rsync -varzH --delete --stats --exclude=".*" --update --password-file restore.secret rsync://rsyncuser@server/backuphandle ~/


# backups from remote can be restored like this:
# rsync -vaxH /media/Backups/remote/remote.2011-01-01.00-00-01/ user@server:
