#!/bin/bash
echo --------------------------------------------------- >> ~/bin/restore-system.log
date >> ~/bin/restore-system.log
# network level rsync - slower but hides the backup folder location
#sudo rsync -varz --delete --delete-excluded --stats --password-file backup-system.secrets --include-from backup-system.include --exclude-from backup-system.exclude --log-file backup-system.log / rsync://rsyncuser@system/somesystembackup
# use file system level rsync
sudo rsync -varz --stats --log-file ~/bin/restore-system.log /media/Backups/some-system/ .
